
x-solr-slave: &solr-slave
  image: solr:9.2.1
  depends_on:
    - solr-master
  environment:
    - SOLR_HEAP=1g
    - SOLR_OPTS=-Dsolr.disable.allowUrls=true
  command:
    - solr-precreate
    - my_core
    - /opt/solr/server/solr/configsets/my_core_conf
  develop:
    watch:
      - action: sync
        path: ./containers/solr/master/conf
        target: /opt/solr/server/solr/configsets/my_core_conf/conf
        x-initialSync: true
  networks:
    - solr-network

services:
  solr-master:
    image: solr:9.2.1
    container_name: solr-master
    ports:
      - "8983:8983"
    volumes:
      - solr_master_data:/var/solr
    environment:
      - SOLR_HEAP=1g
      - SOLR_OPTS=-Dsolr.disable.allowUrls=true
    command:
      - solr-precreate
      - my_core
      - /opt/solr/server/solr/configsets/my_core_conf
    develop:
      watch:
        - action: sync
          path: ./containers/solr/master/conf
          target: /opt/solr/server/solr/configsets/my_core_conf/conf
          x-initialSync: true
    networks:
      - solr-network

  solr-slave1:
    <<: *solr-slave
    ports:
      - 8984:8983
    volumes:
      - solr_slave1_data:/var/solr

networks:
  solr-network:
    driver: bridge

volumes:
  solr_master_data:
  solr_slave1_data:
