x-solr-slave: &solr-slave
  build:
    context: ./containers/solr/slave
  depends_on:
    - solr-master
  environment:
    - SOLR_HEAP=2g
  develop:
    watch:
      - action: sync
        path: ./containers/solr/slave/conf
        target: /opt/solr/server/solr/configsets/my_core_conf/conf
        x-initialSync: true
  networks:
    - solr-network

services:
  solr-master:
    build:
      context: ./containers/solr/master
    container_name: solr-master
    ports:
      - "8983:8983"
    volumes:
      - solr_master_data:/var/solr
    environment:
      - SOLR_HEAP=2g
    develop:
      watch:
        - action: sync
          path: ./containers/solr/master/conf
          target: /opt/solr/server/solr/configsets/my_core_conf/conf
          x-initialSync: true
    networks:
      - solr-network

  solr-slave1:
    <<: *solr-slave
    ports:
      - 8984:8983
    volumes:
      - solr_slave1_data:/var/solr

networks:
  solr-network:
    driver: bridge

volumes:
  solr_master_data:
  solr_slave1_data:
